# Generated by Django 5.2.1 on 2025-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_alter_transaction_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
